M1_DIR=m1
M1_PARTS=$(M1_DIR)/content.tex

include $(M1_DIR)/l1/Makefile.def
include $(M1_DIR)/l2/Makefile.def

M1_BASE=m1
M1_PDF=$(M1_DIR).pdf
FINAL_M1_PDF=$(FINAL_DIR)/$(M1_PDF)

ALL_SLIDES_FINAL_PDF += \
$(FINAL_DIR)/$(M1_PDF) \

